CREATE TABLE CIUDAD (
   ID_Ciudad INT PRIMARY KEY,
   Nombre_Ciudad VARCHAR(45) NOT NULL
);
CREATE TABLE COMUNA (
   ID_Comuna INT PRIMARY KEY,
   Nombre_Comuna VARCHAR(45) NOT NULL,
   FK_ID_Ciudad INT NOT NULL,
   CONSTRAINT FKIDCIU FOREIGN KEY (FK_ID_Ciudad) REFERENCES CIUDAD (ID_Ciudad)
);
CREATE TABLE PLANTA (
   ID_Planta INT PRIMARY KEY,
   Nombre_Planta VARCHAR(45) NOT NULL,
   FK_ID_Comuna INT NOT NULL,
   CONSTRAINT FKIDCOM FOREIGN KEY (FK_ID_Comuna) REFERENCES COMUNA (ID_Comuna)
);
CREATE TABLE PERSONA (
  ID_Persona INT PRIMARY KEY,
  Rut VARCHAR(10) NOT NULL,
  Nombre VARCHAR(30) NOT NULL,
  Apellido_Paterno VARCHAR(30) NOT NULL,
  Apellido_Materno VARCHAR(30),
  Email VARCHAR(60) NOT NULL,
  Telefono VARCHAR(20) NOT NULL
);
CREATE TABLE CLIENTE (
   ID_Cliente INT PRIMARY KEY,
   FK_Comuna INT NOT NULL,
   FK_Persona INT NOT NULL UNIQUE,
   CONSTRAINT FKCOMUNA FOREIGN KEY (FK_Comuna) REFERENCES COMUNA (ID_Comuna),
   CONSTRAINT FKPERSONA FOREIGN KEY (FK_Persona) REFERENCES PERSONA (ID_Persona)
);
CREATE TABLE TIPO_EMPLEADO(
    ID_Tipo INT PRIMARY KEY,
    Nombre_Tipo VARCHAR(30)NOT NULL
);
CREATE TABLE EMPLEADO (
   ID_Empleado INT PRIMARY KEY,
   FK_idTipo_Empleado INT NOT NULL,
   FK_idPlanta INT NOT NULL,
   FK_idPersona INT NOT NULL UNIQUE,
   CONSTRAINT FKTIPEMPL FOREIGN KEY (FK_idTipo_Empleado) REFERENCES TIPO_EMPLEADO (ID_Tipo),
   CONSTRAINT FKPLANTA FOREIGN KEY (FK_idPlanta) REFERENCES PLANTA (ID_Planta),
   CONSTRAINT FKPER FOREIGN KEY (FK_idPersona) REFERENCES PERSONA (ID_Persona)
);
CREATE TABLE RECOLECTOR (
   ID_Recolector INT PRIMARY KEY,
   FK_Empleado INT NOT NULL,
   CONSTRAINT FKEMPLE FOREIGN KEY (FK_Empleado) REFERENCES EMPLEADO (ID_Empleado)
);
CREATE TABLE SUPERVISOR_CALIDAD (
   ID_Supervisor_Calidad INT PRIMARY KEY,
   FK_Empleado INT NOT NULL,
   CONSTRAINT FKSC_E FOREIGN KEY (FK_Empleado) REFERENCES EMPLEADO (ID_Empleado)
);
CREATE TABLE SUPERVISOR_LINEA (
   ID_Supervisor_Linea INT PRIMARY KEY,
   FK_Empleado INT NOT NULL,
   CONSTRAINT FKSL_E FOREIGN KEY (FK_Empleado) REFERENCES EMPLEADO (ID_Empleado)
);
CREATE TABLE FRUTA_PODRIDA(
    ID_FRUTA_PODRIDA INT PRIMARY KEY,
    CANTIDAD INT NOT NULL,
    FECHA_RECOLECCION DATE NOT NULL,
    FK_RECOLECTOR INT NOT NULL,
    CONSTRAINT FKFP_REC FOREIGN KEY(FK_RECOLECTOR) REFERENCES RECOLECTOR(ID_Recolector)
);
CREATE TABLE STOCK_FRUTA (
   ID_Stock INT PRIMARY KEY,
   Numero_Toneladas INT NOT NULL
);
CREATE TABLE CALIDAD_FRUTA (
   ID_Calidad INT PRIMARY KEY,
   Tipo_Calidad VARCHAR(45)NOT NULL
);
CREATE TABLE CAJA_FRUTA (
   idCaja_Fruta INT PRIMARY KEY,
   Peso_Caja INT NOT NULL,
   Fecha_Caja TIMESTAMP,
   FK_ID_Recolector INT NOT NULL,
   FK_idSupervisor_Calidad INT NOT NULL,
   FK_idCalidad_Fruta INT NOT NULL,
   FK_idStock_Fruta INT NOT NULL,
   CONSTRAINT FKCF_R FOREIGN KEY (FK_ID_Recolector) REFERENCES RECOLECTOR (ID_Recolector),
   CONSTRAINT FKCF_SC FOREIGN KEY (FK_idSupervisor_Calidad) REFERENCES SUPERVISOR_CALIDAD (ID_Supervisor_Calidad),
   CONSTRAINT FKCF_CF FOREIGN KEY (FK_idCalidad_Fruta) REFERENCES CALIDAD_FRUTA (ID_Calidad),
   CONSTRAINT FKCF_SF FOREIGN KEY (FK_idStock_Fruta) REFERENCES STOCK_FRUTA (ID_Stock)
);

CREATE TABLE PEDIDO (
   idPedido INT PRIMARY KEY,
   Descripcion_Pedido VARCHAR(45) NOT NULL,
   Cantidad_Pedido INT NOT NULL,
   FK_Cliente INT NOT NULL,
   FK_idSupervisor_Linea INT NOT NULL,
   FK_Calidad_Fruta INT NOT NULL,
   CONSTRAINT FKPRC FOREIGN KEY (FK_Cliente) REFERENCES CLIENTE (ID_Cliente),
   CONSTRAINT FKPSL FOREIGN KEY (FK_idSupervisor_Linea) REFERENCES SUPERVISOR_LINEA (ID_Supervisor_Linea),
   CONSTRAINT FKPCL FOREIGN KEY (FK_Calidad_Fruta) REFERENCES CALIDAD_FRUTA (ID_Calidad)
);
CREATE TABLE REPARTIDOR (
   ID_Repartidor INT PRIMARY KEY,
   FK_EMPLEADO INT NOT NULL,
   CONSTRAINT FKEMPLEADO FOREIGN KEY (FK_EMPLEADO) REFERENCES EMPLEADO (ID_Empleado)
);
CREATE TABLE CAMION (
   Patente VARCHAR(12) PRIMARY KEY,
   Capacidad_Maxima VARCHAR(30) NOT NULL,
   FK_REPARTIDOR INT NOT NULL,
   FK_Planta INT NOT NULL,
   CONSTRAINT FKREPA FOREIGN KEY (FK_REPARTIDOR) REFERENCES REPARTIDOR (ID_Repartidor),
   CONSTRAINT FKPLANT FOREIGN KEY (FK_Planta) REFERENCES PLANTA (ID_PLANTA)
);
CREATE TABLE RUTA_ENTREGA (
   idRuta_Entrega INT PRIMARY KEY,
   Descripcion_Ruta VARCHAR(60),
   FK_Supervisor_Linea INT NOT NULL,
   FK_Camion VARCHAR(12) NOT NULL,
   CONSTRAINT FKRE_SL FOREIGN KEY (FK_Supervisor_Linea) REFERENCES SUPERVISOR_LINEA (ID_Supervisor_Linea),
   CONSTRAINT FKRE_CAM FOREIGN KEY (FK_Camion) REFERENCES CAMION (Patente)
);

CREATE TABLE CALIDAD_FRUTA_LOG (
    idCalidad_Fruta_Log INT PRIMARY KEY,
    Tipo_Calidad_Fruta_Log VARCHAR(30),
    FK_idCalidad_Fruta INT,
    CONSTRAINT FKCFL_CF FOREIGN KEY (FK_idCalidad_Fruta) REFERENCES CALIDAD_FRUTA (idCalidad_Fruta)
);

ALTER TABLE CALIDAD_FRUTA ADD ESTADO VARCHAR(30);
ALTER TABLE CALIDAD_FRUTA_LOG ADD ESTADO VARCHAR(30);

INSERT INTO CALIDAD_FRUTA (ID_Calidad, Tipo_Calidad) VALUES (1, 'En Preparacion');

CREATE OR REPLACE TRIGGER CALIDAD_FRUTA
AFTER UPDATE OF ESTADO ON CALIDAD_FRUTA

FOR EACH ROW
BEGIN
     INSERT INTO CALIDAD_FRUTA_LOG(idCalidad_Fruta_Log, Tipo_Calidad_Fruta_Log, Estado)
     VALUES (:NEW.ID_Calidad, SYSDATE, :OLD.Estado, :NEW.Estado, 'Buena');
END;

UPDATE TABLE CALIDAD_FRUTA SET ESTADO = BUENA WHERE idCalidad_Fruta = 1;

SELECT * FROM CALIDAD_FRUTA;
SELECT * FROM CALIDAD_FRUTA_LOG;

CREATE TABLE STOCK_FRUTA_LOG (
   idStock_Fruta_Log INT PRIMARY KEY,
   Cantidad_Toneladas_Log INT,
   Dia_Stock INT,
   Descripcion VARCHAR(50),
   FK_ID_Stock INT,
   CONSTRAINT FKSFL_SF FOREIGN KEY (FK_ID_Stock) REFERENCES STOCK_FRUTA (ID_Stock)
);

INSERT INTO STOCK_FRUTA (ID_Stock, Numero_Toneladas) VALUES (1, 100);

ALTER TABLE STOCK_FRUTA ADD DIA_STOCK INT;
ALTER TABLE STOCK_FRUTA ADD DESCRIPCION VARCHAR(50);

CREATE OR REPLACE TRIGGER STOCK_FRUTA
AFTER UPDATE OF DIA_STOCK ON STOCK_FRUTA

FOR EACH ROW
BEGIN
     INSERT INTO STOCK_FRUTA_LOG(idStock_Fruta_Log, Cantidad_Toneladas_Log, Dia_Stock, Descripcion)
     VALUES (:NEW.ID_Stock, SYSDATE, :OLD.Numero_Toneladas, :NEW.Numero_Toneladas, '200', :OLD.Dia_Stock, :NEW.Dia_Stock, '2');
END;

UPDATE TABLE STOCK_FRUTA SET DIA_STOCK = '2' WHERE idStock_Fruta = 1;

SELECT * FROM STOCK_FRUTA;
SELECT * FROM STOCK_FRUTA_LOG;

CREATE USER SUPERVISOR_LINEA IDENTIFIED BY 1234;
GRANT RESOURCE, CONNECT, UNLIMITED TABLESPACE TO SUPERVISOR_LINEA;

CREATE USER SUPERVISOR_CALIDAD IDENTIFIED BY 1234;
GRANT RESOURCE, CONNECT, UNLMITED TABLESPACE TO SUPERVISOR_CALIDAD;

CREATE USER RECOLECTOR IDENTIFIED BY 1234;
GRANT RESOURCE, CONNECT, UNLIMITED TABLESPACE TO RECOLECTOR;

DROP USER SUPERVISOR_LINEA;
DROP USER SUPERVISOR_CALIDAD;
DROP USER RECOLECTOR;

AUDIT INSERT, UPDATE, DELETE ON RECOLECTOR.FRUTA_PODRIDA BY ACCESS;

INSERT INTO CAJA_FRUTA (idCaja_Fruta, Peso_Caja, Fecha_Caja, FK_idRecolector, FK_idSupervisor_Calidad, FK_idCalidad_Fruta, FK_idStock_Fruta) VALUES (170, 30, '26/08/2021', 150, 100, 50, 35);

CREATE TABLE CAJA_FRUTA_LOG (
PEDIDO_FECHA DATE,
PEDIDO_ANTERIOR INT, 
PEDIDO_NUEVO INT
);

CREATE OR REPLACE TRIGGER CAJA_FRUTA
AFTER UPDATE OF FK_PEDIDO ON CAJA_FRUTA

FOR EACH ROW
BEGIN
      INSERT INTO CAJA_FRUTA_LOG(PEDIDO_FECHA, PEDIDO_ANTERIOR, PEDIDO_NUEVO) VALUES (SYSDATE, :OLD.FK_PEDIDO, :NEW.FK_PEDIDO);
END;

ALTER TABLE CAJA_FRUTA ADD FK_PEDIDO INT;










CREATE USER SUPERVISOR_LINEA IDENTIFIED BY 1234;
GRANT RESOURCE, CONNECT, UNLIMITED TABLESPACE TO SUPERVISOR_LINEA;

CREATE USER SUPERVISOR_CALIDAD IDENTIFIED BY 1234;
GRANT RESOURCE, CONNECT, UNLIMITED TABLESPACE TO SUPERVISOR_CALIDAD;

CREATE USER RECOLECTOR IDENTIFIED BY 1234;
GRANT RESOURCE, CONNECT, UNLIMITED TABLESPACE TO RECOLECTOR;

CREATE PROFILE RECOLECTOR LIMIT
CPU_PER_SESSION 15000
CONNECT_TIME 30
IDLE_TIME 5
PRIVATE_SGA UNLIMITED
SESSIONS_PER_USER 3
FAILED_LOGIN_ATTEMPTS 3
PASSWORD_LOCK_TIME 1
PASSWORD_LIFE_TIME 30
PASSWORD_GRACE_TIME 5
PASSWORD_REUSE_TIME 7
PASSWORD_REUSE_MAX 3
PASSWORD_VERIFY_FUNCTION NULL;

CREATE ROLE RECOLECTOR;
GRANT CONNECT TO RECOLECTOR;
GRANT RESOURCE TO RECOLECTOR;
GRANT SELECT ON [dbo] TO RECOLECTOR;