CREATE PROFILE CUENTA_COMUN LIMIT
CPU_PER_SESSION 10000
CONNECT_TIME 60
IDLE_TIME 10
PRIVATE_SGA 20M
FAILED_LOGIN_ATTEMPTS 5
PASSWORD_LOCK_TIME 3
PASSWORD_LIFE_TIME 90
PASSWORD_GRACE_TIME 10
PASSWORD_REUSE_TIME 15
PASSWORD_REUSE_MAX 5
PASSWORD_VERIFY_FUNCTION NULL;

CREATE PROFILE CUENTA_ADMINISTRADOR LIMIT
CPU_PER_SESSION 15000
CONNECT_TIME 30
IDLE_TIME 5
PRIVATE_SGA UNLIMITED
SESSIONS_PER_USER 3
FAILED_LOGIN_ATTEMPTS 3
PASSWORD_LOCK_TIME 1
PASSWORD_LIFE_TIME 30
PASSWORD_GRACE_TIME 5
PASSWORD_REUSE_TIME 7
PASSWORD_REUSE_MAX 3
PASSWORD_VERIFY_FUNCTION NULL;

CREATE ROLE DISENADOR;
CONNECT, GRANT RESOURCE TO DISENADOR;

CREATE ROLE PROGRAMADOR;
CONNECT, GRANT CREATE USER, GRANT CREATE ROLE, GRANT CREATE PROFILE, GRANT PERMISSION, GRANT ROLE, UPDATE ROLE, SELECT ROLE, DELETE ROLE TO PROGRAMADOR;

CREATE ROLE SUPERVISOR;
GRANT RESOURCE, GRANT CREATE USER, GRANT ROLE, UPDATE ROLE, SELECT ROLE TO SUPERVISOR;

CREATE USER ELENA IDENTIFIED BY 1234;
ALTER USER ELENA ROLE DISENADOR;
ALTER USER ELENA PROFILE CUENTA_COMUN;

CREATE USER HECTOR IDENTIFIED BY 1234;
ALTER USER HECTOR ROLE PROGRAMADOR;
ALTER USER HECTOR PROFILE CUENTA_COMUN;

CREATE USER MINERVA IDENTIFIED BY 1234;
ALTER USER MINERVA ROLE SUPERVISOR;
ALTER USER MINERVA PROFILE CUENTA_ADMINISTRADOR;