DROP TABLE EVALUACION;

CREATE TABLE PLATO(
ID_PLATO INT PRIMARY KEY,
NOMBRE_PLATO VARCHAR(10) NOT NULL,
DESCRIPCION CHAR(10) NOT NULL,
NIVEL VARCHAR(20) NOT NULL,
FOTO VARCHAR(20) NOT NULL,
PRECIO_FINAL NUMERIC(10),
FK_INGREDIENTE INT NOT NULL,
CONSTRAINT FKPI FOREIGN KEY (FK_INGREDIENTE) REFERENCES INGREDIENTE(ID_INGREDIENTE)
);

CREATE TABLE INGREDIENTE(
ID_INGREDIENTE INT PRIMARY KEY,
NOMBRE_INGREDIENTE VARCHAR(20) NOT NULL,
UNIDADES NUMERIC(10),
CANTIDAD_ALMACEN NUMERIC(10)
);

CREATE TABLE CATEGORIA(
ID_CATEGORIA INT PRIMARY KEY,
NOMBRE_CATEGORIA VARCHAR(10) NOT NULL,
DESCRIPCION CHAR(15) NOT NULL,
NOMBRE_ENCARGADO VARCHAR(20) NOT NULL,
FK_ENCARGADO INT NOT NULL,
CONSTRAINT FKCE FOREIGN KEY (FK_ENCARGADO) REFERENCES ENCARGADO(ID_ENCARGADO)
);

CREATE TABLE FACTURA(
ID_FACTURA INT PRIMARY KEY,
FK_CLIENTE INT NOT NULL,
DETALLE VARCHAR(10) NOT NULL,
FK_PLATO INT NOT NULL,
CONSTRAINT FKFC FOREIGN KEY (FK_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
CONSTRAINT FKFP FOREIGN KEY (FK_PLATO) REFERENCES PLATO(ID_PLATO)
);

CREATE TABLE CLIENTE(
ID_CLIENTE INT PRIMARY KEY,
NOMBRE_CLIENTE VARCHAR(20),
OBSERVACIONES CHAR(10)
);

CREATE TABLE ENCARGADO(
ID_ENCARGADO INT PRIMARY KEY,
NOMBRE_ENCARGADO VARCHAR(20) NOT NULL,
RUT VARCHAR(10) NOT NULL,
DOMICILIO CHAR(10) NOT NULL
);