CREATE ROLE JefeProyecto;
GRANT CONNECT TO JefeProyecto;
GRANT RESOURCE TO JefeProyecto;
GRANT UNLIMITED TABLESPACE TO JefeProyecto;

CREATE ROLE DeveloperProyecto;
GRANT CONNECT TO DeveloperProyecto;
GRANT CREATE TABLE TO DeveloperProyecto;
GRANT CREATE TRIGGER TO DeveloperProyecto;
GRANT CREATE PROCEDURE TO DeveloperProyecto;
GRANT CREATE SEQUENCE TO DeveloperProyecto;
GRANT CREATE ANY VIEW TO DeveloperProyecto;
SELECT * FROM DBA_ROLES;

CREATE ROLE UsuarioCliente;
GRANT CONNECT TO UsuarioCliente;
GRANT SELECT ANY VIEW TO UsuarioCliente;
GRANT SELECT ON CLIENTE2 TO UsuarioCliente;
GRANT SELECT ON ABOGADO TO UsuarioCliente;
GRANT SELECT ON PROCURADOR TO UsuarioCliente;
GRANT INSERT ON CLIENTE2 TO UsuarioCliente;
GRANT INSERT ON ABOGADO TO UsuarioCliente;
GRANT INSERT ON PROCURADOR TO UsuarioCliente;
GRANT UPDATE ON CLIENTE2 TO UsuarioCliente;
GRANT UPDATE ON ABOGADO TO UsuarioCliente;
GRANT UPDATE ON PROCURADOR TO UsuarioCliente;
GRANT DELETE ON CLIENTE2 TO UsuarioCliente;
GRANT DELETE ON ABOGADO TO UsuarioCliente;
GRANT DELETE ON PROCURADOR TO UsuarioCliente;

CREATE PROFILE AntonioProyecto LIMIT
CPU_PER_SESSION 20000
CONNECT_TIME 60
IDLE_TIME 15
PRIVATE_SGA 30M
FAILED_LOGIN_ATTEMPTS 3
PASSWORD_LOCK_TIME 2
PASSWORD_LIFE_TIME 30
PASSWORD_GRACE_TIME 3
PASSWORD_REUSE_MAX 2
SESSIONS_PER_USER 3
LOGICAL_READS_PER_SESSION UNLIMITED
;

CREATE PROFILE AntonioSupervisor LIMIT
CPU_PER_SESSION 10000
CONNECT_TIME 20
IDLE_TIME 10
PRIVATE_SGA 30M
FAILED_LOGIN_ATTEMPTS 3
PASSWORD_LOCK_TIME 1
PASSWORD_LIFE_TIME 30
PASSWORD_GRACE_TIME 5
PASSWORD_REUSE_TIME 7
PASSWORD_REUSE_MAX 3
SESSIONS_PER_USER 1
LOGICAL_READS_PER_SESSION UNLIMITED
;

CREATE USER JefeProyecto_1 IDENTIFIED BY abc123;
CREATE USER DeveloperProyecto_1 IDENTIFIED BY abc123;
CREATE USER UsuarioCliente_1 IDENTIFIED BY abc123;

ALTER USER JefeProyecto_1 PROFILE AntonioProyecto DEFAULT TABLESPACE AntonioAbogados QUOTA 250M ON AntonioAbogados;
ALTER USER DeveloperProyecto_1 PROFILE AntonioProyecto DEFAULT TABLESPACE AntonioAbogados QUOTA 250M ON AntonioAbogados;
ALTER USER UsuarioCliente_1 PROFILE AntonioSupervisor DEFAULT TABLESPACE AntonioAbogados QUOTA 250M ON AntonioAbogados;